@startuml
autoactivate on
hide footbox

actor Gebruiker
participant Speler
participant "s:Speler"
participant Vragenlijst
participant "v:Vragenlijst"

Gebruiker -> Speler : registreren()
    alt success
        Speler -> Speler : validateInformation()
        Speler -> Speler : isUsernameAvailable()
        return usernameAvailable
        Speler -> Speler : isValidPassword()
        return validPassword
        return validInfo
        alt validInfo = true
            Speler -> Speler : createSpeler()
            return s = Speler
            Speler -> "s:Speler" : register()
            "s:Speler" -> "s:Speler" : addCoins(100)
            return
            "s:Speler" -> Vragenlijst : getVragenlijst()
            Vragenlijst -> "v:Vragenlijst" **: create()
            return v = Vragenlijst
            |||
            return
            return Informatie successvol verwerkt
        else validInfo = false
            Speler -[#FFFFFF]> Speler
           Speler --> Gebruiker : Informatie niet correct
        end


@enduml

@startuml
help skinparam
@enduml
